select * from customer limit 20

--Q1. What is the total revenue generated by male vs females?

Select gender, SUM(purchase_amount) as revenue
from customer
group by gender



--Q2. Which customers used a discount but still spent more than the avg purchase amt?

Select customer_id, purchase_amount
From customer
Where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)


  
--Q3. Which are the top 5 products with the highest avg review rating?

SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
From customer
Group by item_purchased
Order by avg(review_rating) desc
limit 5;


--Q4. Compare the average Purchasing Amt between Standard and Express Shipping.

Select shipping_type,
ROUND(AVG(purchase_amount),2)
From customer
Where shipping_type in ('Standard','Express')
Group by shipping_type


--Q5. Do subscribed customers spend more? Compare avg spend and total revenue
--between subscribers and non-subscribers.

Select subscription_status,
COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
From customer
Group by subscription_status
Order by total_revenue, avg_spend desc;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

Select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
From customer
Group by item_purchased
Order by discount_rate desc
Limit 5;


--Q7. Segment customers into New, Returning and Loyal based on their total number of purchasses, and 
-- show count on each segment.
WITH customer_type as(
SELECT customer_id, previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer
)


select customer_segment, count(*) as "Number of customers"
from customer_type
group by customer_segment


--Q8. What are the top 3 most purchased product within each category?

WITH item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) AS item_rank
FROM customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;



--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status


--Q10. What is the revenue contribution of each age group?

select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;







